/*
 */

# include  <unistd.h>
# include  <stdio.h>
# include  <stdlib.h>

static void printf_bytes(size_t nbuf, const unsigned char*buf)
{
      size_t idx, jdx;

      printf("    0x%02x", buf[0]);
      for (jdx = 1 ; jdx < 16 && jdx<nbuf ; jdx += 1)
	    printf(",0x%02x", buf[0+jdx]);
      for (idx = 16 ; idx < nbuf ; idx += 16) {
	    printf(",\n    0x%02x", buf[idx]);
	    for (jdx = 1 ; jdx < 16 && (idx+jdx) < nbuf ; jdx += 1)
		  printf(",0x%02x", buf[idx+jdx]);
      }
}

int main(int argc, char*argv[])
{
      char*input_path = 0;
      char*symbol_name = 0;
      int opt;

      while ( (opt = getopt(argc, argv, "i:s:")) != -1 ) {
	    switch (opt) {
		case 'i':
		  input_path = optarg;
		  break;
		case 's':
		  symbol_name = optarg;
		  break;
		default:
		  fprintf(stderr, "Usage: %s -i <input path> -s <symbol name>\n", argv[0]);
		  return EXIT_FAILURE;
	    }
	    
      }

      if (input_path == 0) {
	    fprintf(stderr, "Input path required. Use -s <input path>\n");
	    return EXIT_FAILURE;
      }

      if (symbol_name == 0) {
	    fprintf(stderr, "Symbol name required. Use 'i <symbol_name>\n");
	    return EXIT_FAILURE;
      }

      FILE*input_fd = fopen(input_path, "rb");
      if (input_fd == 0) {
	    fprintf(stderr, "Unable to open %s for read.\n", input_path);
	    return EXIT_FAILURE;
      }

      printf("/* Auto-generated by bin2carray.c from %s. */\n", input_path);
      printf("unsigned char %s[] = {\n", symbol_name);

      unsigned char buf[1024];
      size_t nbuf = fread(buf, 1, sizeof buf, input_fd);
      printf_bytes(nbuf, buf);
      while (nbuf == sizeof buf) {
	    printf(",\n");
	    nbuf = fread(buf, 1, sizeof buf, input_fd);
	    printf_bytes(nbuf, buf);
      }
      printf("\n};\n");

      fclose(input_fd);
      return 0;
}
