#ifndef _H_PdfStandardAtoms
#define _H_PdfStandardAtoms
#pragma once

#include "PdfElements.h"

#define __ATOM(n) ((t_pdatom)n)

#define PDA_UNDEFINED_ATOM __ATOM(0)
#define PDA_TYPE __ATOM(1)
#define PDA_PAGES __ATOM(2)
#define PDA_SIZE __ATOM(3)
#define PDA_ROOT __ATOM(4)
#define PDA_INFO __ATOM(5)
#define PDA_ID __ATOM(6)
#define PDA_CATALOG __ATOM(7)
#define PDA_PARENT __ATOM(8)
#define PDA_KIDS __ATOM(9)
#define PDA_COUNT __ATOM(10)
#define PDA_PAGE __ATOM(11)
#define PDA_RESOURCES __ATOM(12)
#define PDA_MEDIABOX __ATOM(13)
#define PDA_CROPBOX __ATOM(14)
#define PDA_CONTENTS __ATOM(15)
#define PDA_ROTATE __ATOM(16)
#define PDA_LENGTH __ATOM(17)
#define PDA_FILTER __ATOM(18)
#define PDA_DECODEPARMS __ATOM(19)
#define PDA_SUBTYPE __ATOM(20)
#define PDA_WIDTH __ATOM(21)
#define PDA_HEIGHT __ATOM(22)
#define PDA_BITSPERCOMPONENT __ATOM(23)
#define PDA_COLORSPACE __ATOM(24)
#define PDA_IMAGE __ATOM(25)
#define PDA_XOBJECT __ATOM(26)
#define PDA_TITLE __ATOM(27)
#define PDA_SUBJECT __ATOM(28)
#define PDA_AUTHOR __ATOM(29)
#define PDA_KEYWORDS __ATOM(30)
#define PDA_CREATOR __ATOM(31)
#define PDA_PRODUCER __ATOM(32)
#define PDA_NONE __ATOM(33)
#define PDA_FLATEDECODE __ATOM(34)
#define PDA_CCITTFAXDECODE __ATOM(35)
#define PDA_DCTDECODE __ATOM(36)
#define PDA_JBIG2DECODE __ATOM(37)
#define PDA_JPXDECODE __ATOM(38)
#define PDA_K __ATOM(39)
#define PDA_COLUMNS __ATOM(40)
#define PDA_ROWS __ATOM(41)
#define PDA_BLACKIS1 __ATOM(42)
#define PDA_DEVICEGRAY __ATOM(43)
#define PDA_DEVICERGB __ATOM(44)
#define PDA_DEVICECMYK __ATOM(45)
#define PDA_INDEXED __ATOM(46)
#define PDA_ICCBASED __ATOM(47)
#define PDA_PIECEINFO __ATOM(48)
#define PDA_LASTMODIFIED __ATOM(49)
#define PDA_PRIVATE __ATOM(50)
#define PDA_PDFRASTER __ATOM(51)
#define PDA_PHYSICALPAGENUMBER __ATOM(52)
#define PDA_FRONTSIDE __ATOM(53)
#define PDA_STRIP0 __ATOM(54)

#define LAST_STATIC_ATOM PDA_STRIP0

#endif